/*
 * Kotlin translation of JSXGraph.
 * Upstream: src/themes/dark.js, src/themes/gui.js,
 * src/themes/mono_thin.js
 * Copyright 2008-2026 Matthias Ehmann, Michael Gerhaeuser, Carsten Miller,
 * Bianca Valentin, Andreas Walter, Alfred Wassermann, and Peter Wilfahrt.
 * Used under the MIT License option.
 */
package com.swithun.jsxgraph.core

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

internal object JsxGraphThemes {
    // JSXGraph 1.13.3: src/themes/dark.js.
    internal val darkOptionsPatch = optionTree(
        "board.showCopyright" to false,
        "board.showNavigation" to false,
        "board.showInfobox" to true,
        "navbar.strokeColor" to "#bbb",
        "navbar.fillColor" to "none",
        "elements.strokeColor" to "#6BBA70",
        "elements.highlightStrokeColor" to "#84e68a",
        "elements.fillColor" to "none",
        "elements.highlightFillColor" to "none",
        "elements.strokeOpacity" to 0.6,
        "elements.highlightStrokeOpacity" to 1,
        "point.face" to "o",
        "point.size" to 4,
        "point.fillColor" to "#eeeeee",
        "point.highlightFillColor" to "#eeeeee",
        "point.strokeColor" to "white",
        "point.highlightStrokeColor" to "white",
        "point.showInfobox" to "inherit",
        "line.strokeColor" to "#eee",
        "line.highlightStrokeColor" to "white",
        "line.ticks.drawLabels" to true,
        "line.ticks.drawZero" to false,
        "line.ticks.insertTicks" to false,
        "line.ticks.ticksDistance" to 1,
        "line.ticks.minTicksDistance" to 50,
        "line.ticks.minorHeight" to 4,
        "line.ticks.majorHeight" to 10,
        "line.ticks.minorTicks" to 4,
        "line.labelOffsets" to listOf(10, 10),
        "axis.strokeColor" to "#aaa",
        "axis.highlightStrokeColor" to "#aaa",
        "circle.fillColor" to "none",
        "circle.highlightFillColor" to "none",
        "circle.strokeColor" to "#0000ff",
        "circle.highlightStrokeColor" to "#C3D9FF",
        "conic.fillColor" to "none",
        "conic.highlightFillColor" to "none",
        "conic.strokeColor" to "#0000ff",
        "conic.highlightStrokeColor" to "#C3D9FF",
        "angle.withLabel" to true,
        "angle.radius" to 1,
        "angle.fillColor" to "#FF7F00",
        "angle.highlightFillColor" to "#FF7F00",
        "angle.strokeColor" to "#FF7F00",
        "angle.textColor" to "#0000FF",
        "angle.fillOpacity" to 0.3,
        "angle.highlightFillOpacity" to 0.3,
        "arc.firstArrow" to false,
        "arc.lastArrow" to false,
        "arc.fillColor" to "none",
        "arc.highlightFillColor" to "none",
        "arc.strokeColor" to "#0000ff",
        "arc.highlightStrokeColor" to "#C3D9FF",
        "polygon.fillColor" to "#6BBA70",
        "polygon.highlightFillColor" to "#6BBA70",
        "polygon.fillOpacity" to 0.3,
        "polygon.highlightFillOpacity" to 0.3,
        "polygon.borders.withLabel" to false,
        "polygon.borders.highlightStrokeColor" to "#eee",
        "polygon.borders.layer" to 5,
        "text.fontSize" to 10,
        "text.strokeColor" to "gray",
        "text.useASCIIMathML" to false,
        "text.useMathJax" to false,
        "text.defaultDisplay" to "html",
        "curve.strokeWidth" to 2,
        "curve.strokeColor" to "#6BBA70",
        "slider.withTicks" to false,
        "slider.fillColor" to "#eeeeee",
        "slider.highlightFillColor" to "#eeeeee",
        "slider.strokeColor" to "white",
        "slider.highlightStrokeColor" to "white",
        "slider.size" to 6,
        "slider.face" to "<>",
        "slider.baseline.needsRegularUpdate" to false,
        "slider.baseline.name" to "",
        "slider.baseline.strokeWidth" to 1,
        "slider.baseline.strokeColor" to "#ddd",
        "slider.baseline.highlightStrokeColor" to "#ddd",
        "slider.ticks.needsRegularUpdate" to false,
        "slider.ticks.drawLabels" to false,
        "slider.ticks.drawZero" to true,
        "slider.ticks.insertTicks" to true,
        "slider.ticks.ticksDistance" to 1,
        "slider.ticks.minorHeight" to 4,
        "slider.ticks.majorHeight" to 10,
        "slider.ticks.minorTicks" to 0,
        "slider.ticks.opacity" to 1,
        "slider.ticks.strokeWidth" to 2,
        "slider.ticks.strokeColor" to "#ddd",
        "slider.highline.strokeWidth" to 5,
        "slider.highline.name" to "",
        "slider.highline.strokeColor" to "#eee",
        "slider.highline.highlightStrokeColor" to "#eee",
        "slider.label.strokeColor" to "#ccc",
        "chart.fillOpacity" to 0.6,
        "trunclen" to 2,
    )

    // JSXGraph 1.13.3: src/themes/gui.js.
    internal val guiOptionsPatch = optionTree(
        "device" to "tablet",
        "opacityLevel" to 0.5,
        "sensitive_area" to 20,
        "lastRegPolCorners" to 4,
        "lastSliderStart" to -10,
        "lastSliderEnd" to 10,
        "lastSliderIni" to 1,
        "board.minimizeReflow" to "svg",
        "board.zoom.enabled" to true,
        "board.zoom.wheel" to true,
        "board.zoom.needShift" to true,
        "board.zoom.pinchHorizontal" to false,
        "board.zoom.pinchVertical" to false,
        "board.pan.needShift" to true,
        "board.pan.needTwoFingers" to true,
        "board.pan.enabled" to true,
        "board.selection.enabled" to false,
        "angle.fillColor" to "#ddd",
        "angle.strokeColor" to "#000",
        "angle.strokeWidth" to 1,
        "angle.radius" to 1,
        "angle.orthotype" to "sectordot",
        "axis.scalable" to false,
        "axis.ticks.strokeColor" to "#aaa",
        "axis.ticks.strokeOpacity" to 0.4,
        "axis.ticks.minorHeight" to -1,
        "axis.ticks.label.fontSize" to 14,
        "axis.ticks.label.display" to "internal",
        "axis.label.position" to "urt",
        "axis.label.offset" to listOf(-15, 30),
        "axis.label.display" to "internal",
        "circle.strokeColor" to "#36f",
        "circle.strokeOpacity" to 0.9,
        "circle.strokeWidth" to 3,
        "curve.RDPSmoothing" to false,
        "curve.strokeWidth" to 3,
        "curve.strokeOpacity" to 0.9,
        "curve.recursionDepthLow" to 7,
        "curve.recursionDepthHigh" to 17,
        "elements.transitionDuration" to 170,
        "glider.strokeColor" to "orange",
        "glider.fillColor" to "orange",
        "glider.opacity" to 1,
        "intersection.strokeColor" to "#808080",
        "intersection.fillColor" to "#808080",
        "intersection.opacity" to 1,
        "label.offset" to listOf(12, 12),
        "label.autoPosition" to true,
        "line.strokeColor" to "#36f",
        "line.strokeOpacity" to 0.9,
        "line.strokeWidth" to 3,
        "line.scalable" to false,
        "midpoint.strokeColor" to "#808080",
        "midpoint.fillColor" to "#808080",
        "midpoint.opacity" to 1,
        "perpendicularsegment.point.visible" to true,
        "perpendicularsegment.point.strokeColor" to "#808080",
        "perpendicularsegment.point.fillColor" to "#808080",
        "perpendicularsegment.point.opacity" to 1,
        "point.size" to 4,
        "point.fillColor" to "#cc0000",
        "point.strokeColor" to "#cc0000",
        "point.strokeOpacity" to 0.9,
        "point.highlightFillColor" to "#cc0000",
        "point.highlightStrokeColor" to "#cc0000",
        "point.highlightFillOpacity" to 0.4,
        "point.highlightStrokeOpacity" to 0.4,
        "point.snapX" to -1,
        "point.snapY" to -1,
        "point.snapsizeX" to 0.5,
        "point.snapsizeY" to 0.5,
        "polygon.fillColor" to "#ffff00",
        "polygon.highlightFillColor" to "#ffff00",
        "polygon.hasInnerPoints" to true,
        "polygon.scalable" to false,
        "polygon.borders.strokeColor" to "#444444",
        "polygon.borders.strokeOpacity" to 0.9,
        "polygon.borders.strokeWidth" to 2,
        "polygon.borders.fixed" to true,
        "precision.touchMax" to Double.POSITIVE_INFINITY,
        "sector.strokeWidth" to 0,
        "sector.highlightStrokeWidth" to 0,
        "sector.arc.visible" to true,
        "sector.arc.fillColor" to "none",
        "segment.label.position" to "bot",
        "segment.label.offsets" to listOf(0, -12),
        "segment.scalable" to false,
        "slider.highlightFillColor" to "#ffffff",
        "slider.strokeOpacity" to 0.5,
        "slider.strokeColor" to "#444444",
        "slider.face" to "[]",
        "slider.ticks.tickEndings" to listOf(0, 1),
        "slider.ticks.minTicksDistance" to 15,
        "slider.ticks.strokeColor" to "#444444",
        "slider.ticks.strokeOpacity" to 0.5,
        "slider.ticks.highlightStrokeColor" to "#444444",
        "slider.ticks.highlightStrokeOpacity" to 0.5,
        "slider.ticks.needsRegularUpdate" to true,
        "slider.ticks.fixed" to false,
        "slider.baseline.strokeColor" to "#444444",
        "slider.baseline.highlightStrokeColor" to "#444444",
        "slider.baseline.strokeOpacity" to 0.5,
        "slider.baseline.highlightStrokeOpacity" to 0.5,
        "slider.baseline.needsRegularUpdate" to true,
        "slider.baseline.fixed" to false,
        "slider.baseline.scalable" to false,
        "slider.highline.strokeColor" to "#444444",
        "slider.highline.highlightStrokeColor" to "#444444",
        "slider.highline.strokeOpacity" to 0.5,
        "slider.highline.highlightStrokeOpacity" to 0.5,
        "slider.highline.needsRegularUpdate" to true,
        "slider.point1.fixed" to false,
        "slider.point1.needsRegularUpdate" to true,
        "slider.point1.snapToGrid" to true,
        "slider.point1.strokeColor" to "#444444",
        "slider.point1.highlightStrokeColor" to "#444444",
        "slider.point1.fillColor" to "#444444",
        "slider.point1.highlightFillColor" to "#444444",
        "slider.point1.strokeOpacity" to 0.5,
        "slider.point1.highlightStrokeOpacity" to 0.5,
        "slider.point1.size" to 3,
        "slider.point2.fixed" to false,
        "slider.point2.needsRegularUpdate" to true,
        "slider.point2.snapToGrid" to true,
        "slider.point2.strokeColor" to "#444444",
        "slider.point2.highlightStrokeColor" to "#444444",
        "slider.point2.fillColor" to "#444444",
        "slider.point2.highlightFillColor" to "#444444",
        "slider.point2.strokeOpacity" to 0.5,
        "slider.point2.highlightStrokeOpacity" to 0.5,
        "slider.point2.size" to 3,
        "slopetriangle.glider.strokeColor" to "#808080",
        "slopetriangle.glider.fillColor" to "#808080",
        "slopetriangle.glider.opacity" to 1,
        "slopetriangle.glider.visible" to true,
        "slopetriangle.toppoint.strokeColor" to "#808080",
        "slopetriangle.toppoint.fillColor" to "#808080",
        "slopetriangle.toppoint.opacity" to 1,
        "slopetriangle.toppoint.visible" to true,
        "tapemeasure.strokeColor" to "#000000",
        "tapemeasure.strokeWidth" to 2,
        "tapemeasure.highlightStrokeColor" to "#000000",
        "tapemeasure.strokeOpacity" to 0.7,
        "tapemeasure.point1.strokeOpacity" to 0.7,
        "tapemeasure.point1.snapToPoints" to true,
        "tapemeasure.point1.attractorUnit" to "screen",
        "tapemeasure.point1.attractorDistance" to 20,
        "tapemeasure.point2.strokeOpacity" to 0.7,
        "tapemeasure.point2.snapToPoints" to true,
        "tapemeasure.point2.attractorUnit" to "screen",
        "tapemeasure.point2.attractorDistance" to 20,
        "tapemeasure.ticks.strokeOpacity" to 0.7,
        "text.fontSize" to 18,
        "text.strokeColor" to "#222",
        "text.highlightStrokeColor" to "#222",
        "text.strokeOpacity" to 1,
        "text.highlightStrokeOpacity" to 0.66666,
        "text.digits" to 2,
        "trunclen" to 2,
    )

    // JSXGraph 1.13.3: src/themes/mono_thin.js.
    internal val monoThin = optionTree(
        "board.showInfobox" to false,
        "board.showCopyright" to true,
        "board.defaultAxes.x.ticks.minorTicks" to 0,
        "board.defaultAxes.x.ticks.majorHeight" to 10,
        "board.defaultAxes.x.ticks.majorTickEndings" to listOf(1, 0),
        "board.defaultAxes.y.ticks.minorTicks" to 0,
        "board.defaultAxes.y.ticks.majorHeight" to 10,
        "board.defaultAxes.y.ticks.majorTickEndings" to listOf(0, 1),
        "navbar.strokeColor" to "#bbb",
        "navbar.fillColor" to "none",
        "elements.strokeColor" to "#000",
        "elements.highlightStrokeColor" to "#000",
        "elements.fillColor" to "none",
        "elements.highlightFillColor" to "none",
        "elements.strokeOpacity" to 0.6,
        "elements.highlightStrokeOpacity" to 1,
        "angle.strokeColor" to "#000",
        "angle.fillColor" to "#aaaaaa55",
        "angle.fillOpacity" to 0.3,
        "angle.highlightFillColor" to "#aaaaaa33",
        "angle.highlightFillOpacity" to 0.3,
        "angle.label.strokeColor" to "#000",
        "arc.strokeColor" to "#000",
        "arc.strokeWidth" to 0.75,
        "arc.highlightStrokeColor" to "#000",
        "arc.highlightStrokeWidth" to 0.75,
        "boxplot.strokeWidth" to 0.75,
        "boxplot.strokeColor" to "#000",
        "boxplot.fillColor" to "#000",
        "boxplot.fillOpacity" to 0.2,
        "boxplot.highlightStrokeWidth" to 0.75,
        "boxplot.highlightStrokeColor" to "#000",
        "boxplot.highlightFillColor" to "#000",
        "boxplot.highlightFillOpacity" to 0.1,
        "circle.strokeWidth" to 0.75,
        "circle.highlightStrokeWidth" to 1.125,
        "circle.strokeColor" to "#000",
        "circle.highlightFillColor" to "none",
        "circle.highlightStrokeColor" to "#000",
        "circle.center.size" to 0.75,
        "circle.center.fillColor" to "#000",
        "circle.center.strokeColor" to "#000",
        "circle.center.highlightStrokeWidth" to 3,
        "circle.center.highlightFillColor" to "#000",
        "circle.center.highlightStrokeColor" to "#000",
        "circle.point2.size" to 0.75,
        "circle.point2.fillColor" to "#000",
        "circle.point2.strokeColor" to "#000",
        "circle.point2.highlightStrokeWidth" to 3,
        "circle.point2.highlightFillColor" to "#000",
        "circle.point2.highlightStrokeColor" to "#000",
        "circumcircle.strokeWidth" to 0.75,
        "circumcircle.highlightStrokeWidth" to 1.125,
        "circumcircle.strokeColor" to "#000",
        "circumcircle.highlightFillColor" to "none",
        "circumcircle.highlightStrokeColor" to "#000",
        "circumcircle.center.size" to 0.75,
        "circumcircle.center.fillColor" to "#000",
        "circumcircle.center.strokeColor" to "#000",
        "circumcircle.center.highlightStrokeWidth" to 3,
        "circumcircle.center.highlightFillColor" to "#000",
        "circumcircle.center.highlightStrokeColor" to "#000",
        "circumcirclearc.strokeColor" to "#000",
        "circumcirclearc.strokeWidth" to 0.75,
        "circumcirclearc.highlightStrokeColor" to "#000",
        "circumcirclearc.highlightStrokeWidth" to 0.75,
        "circumcirclesector.strokeColor" to "#000",
        "circumcirclesector.fillColor" to "#aaaaaa55",
        "circumcirclesector.fillOpacity" to 0.3,
        "circumcirclesector.highlightFillColor" to "#aaaaaa33",
        "circumcirclesector.highlightFillOpacity" to 0.3,
        "comb.strokeColor" to "#000",
        "comb.strokeWidth" to 0.75,
        "conic.strokeWidth" to 0.75,
        "conic.highlightStrokeWidth" to 1.125,
        "conic.strokeColor" to "#000",
        "conic.highlightStrokeColor" to "#000",
        "conic.fillColor" to "none",
        "conic.highlightFillColor" to "none",
        "curve.strokeColor" to "#000",
        "curve.strokeWidth" to 0.75,
        "curve.highlightStrokeColor" to "#000",
        "curve.highlightStrokeWidth" to 0.75,
        "grid.strokeWidth" to 0.75,
        "hatch.strokeColor" to "#000",
        "hatch.strokeWidth" to 0.75,
        "incircle.strokeWidth" to 0.75,
        "incircle.highlightStrokeWidth" to 1.125,
        "incircle.strokeColor" to "#000",
        "incircle.highlightFillColor" to "none",
        "incircle.highlightStrokeColor" to "#000",
        "incircle.center.size" to 0.75,
        "incircle.center.fillColor" to "#000",
        "incircle.center.strokeColor" to "#000",
        "incircle.center.highlightStrokeWidth" to 3,
        "incircle.center.highlightFillColor" to "#000",
        "incircle.center.highlightStrokeColor" to "#000",
        "inequality.fillColor" to "#aaaaaa55",
        "inequality.fillOpacity" to 0.2,
        "integral.fillColor" to "#aaaaaa55",
        "integral.highlightFillColor" to "#aaaaa33",
        "integral.fillOpacity" to 0.3,
        "integral.highlightFillOpacity" to 0.3,
        "integral.curveLeft.color" to "#000",
        "integral.baseLeft.color" to "#000",
        "integral.curveRight.color" to "#000",
        "integral.baseRight.color" to "#000",
        "label.strokeColor" to "#000",
        "line.strokeColor" to "#000",
        "line.strokeWidth" to 0.75,
        "line.highlightStrokeColor" to "#000",
        "line.highlightStrokeWidth" to 0.75,
        "line.point1.size" to 0.75,
        "line.point1.fillColor" to "#000",
        "line.point1.strokeColor" to "#000",
        "line.point1.highlightStrokeWidth" to 3,
        "line.point1.highlightFillColor" to "#000",
        "line.point1.highlightStrokeColor" to "#000",
        "line.point2.size" to 0.75,
        "line.point2.fillColor" to "#000",
        "line.point2.strokeColor" to "#000",
        "line.point2.highlightStrokeWidth" to 3,
        "line.point2.highlightFillColor" to "#000",
        "line.point2.highlightStrokeColor" to "#000",
        "normal.strokeColor" to "#000",
        "parallel.strokeColor" to "#000",
        "perpendicular.strokeColor" to "#000",
        "perpendicularsegment.strokeColor" to "#000",
        "point.size" to 0.75,
        "point.fillColor" to "#000",
        "point.strokeColor" to "#000",
        "point.highlightStrokeWidth" to 3,
        "point.highlightFillColor" to "#000",
        "point.highlightStrokeColor" to "#000",
        "polygon.fillColor" to "#aaaaaa55",
        "polygon.highlightFillColor" to "#aaaaaa33",
        "polygon.fillOpacity" to 0.3,
        "polygon.highlightFillOpacity" to 0.3,
        "polygon.vertices.size" to 0.75,
        "polygon.vertices.fillColor" to "#000",
        "polygon.vertices.strokeColor" to "#000",
        "polygon.vertices.highlightStrokeWidth" to 3,
        "polygon.vertices.highlightFillColor" to "#000",
        "polygon.vertices.highlightStrokeColor" to "#000",
        "polygon.borders.strokeColor" to "#000",
        "polygon.borders.strokeWidth" to 0.75,
        "polygon.borders.highlightStrokeColor" to "#000",
        "polygon.borders.highlightStrokeWidth" to 0.75,
        "sector.strokeColor" to "#000",
        "sector.fillColor" to "#aaaaaa55",
        "sector.fillOpacity" to 0.3,
        "sector.highlightFillColor" to "#aaaaaa33",
        "sector.highlightFillOpacity" to 0.3,
        "semicircle.center.size" to 0.75,
        "semicircle.center.fillColor" to "#000",
        "semicircle.center.strokeColor" to "#000",
        "semicircle.center.highlightStrokeWidth" to 3,
        "semicircle.center.highlightFillColor" to "#000",
        "semicircle.center.highlightStrokeColor" to "#000",
        "slider.size" to 0.75,
        "slider.fillColor" to "#000",
        "slider.strokeColor" to "#000",
        "slider.highlightStrokeWidth" to 3,
        "slider.highlightFillColor" to "#000",
        "slider.highlightStrokeColor" to "#000",
        "slider.baseline.strokeWidth" to 0.75,
        "slider.baseline.strokeColor" to "#000",
        "slider.baseline.highlightStrokeColor" to "#000",
        "slider.label.strokeColor" to "#000",
        "slider.highline.strokeWidth" to 2.25,
        "slider.highline.name" to "",
        "slider.highline.strokeColor" to "#000",
        "slider.highline.highlightStrokeColor" to "#000",
        "slider.ticks.strokeColor" to "#000",
        "slopefield.strokeWidth" to 0.5625,
        "slopefield.highlightStrokeWidth" to 0.75,
        "slopefield.highlightStrokeColor" to "#000",
        "slopefield.highlightStrokeOpacity" to 0.8,
        "tapemeasure.strokeColor" to "#000",
        "tapemeasure.strokeWidth" to 0.75,
        "tapemeasure.highlightStrokeColor" to "#000",
        "tapemeasure.highlightStrokeWidth" to 0.75,
        "tapemeasure.point1.size" to 0.75,
        "tapemeasure.point1.fillColor" to "#000",
        "tapemeasure.point1.strokeColor" to "#000",
        "tapemeasure.point1.highlightStrokeWidth" to 3,
        "tapemeasure.point1.highlightFillColor" to "#000",
        "tapemeasure.point1.highlightStrokeColor" to "#000",
        "tapemeasure.point2.size" to 0.75,
        "tapemeasure.point2.fillColor" to "#000",
        "tapemeasure.point2.strokeColor" to "#000",
        "tapemeasure.point2.highlightStrokeWidth" to 3,
        "tapemeasure.point2.highlightFillColor" to "#000",
        "tapemeasure.point2.highlightStrokeColor" to "#000",
        "tapemeasure.ticks.strokeWidth" to 0.75,
        "text.strokeColor" to "#000",
        "tracecurve.strokeColor" to "#000",
        "turtle.strokeWidth" to 0.75,
        "turtle.strokeColor" to "#000",
        "turtle.arrow.strokeWidth" to 1.5,
        "turtle.arrow.strokeColor" to "#aaaaaa55",
        "vectorfield.strokeWidth" to 0.5625,
        "vectorfield.highlightStrokeWidth" to 0.75,
        "vectorfield.highlightStrokeColor" to "#000",
        "vectorfield.highlightStrokeOpacity" to 0.8,
    )

    internal fun registeredTheme(name: String): JsonObject? =
        when (name) {
            "mono_thin" -> monoThin
            else -> null
        }

    internal fun elementDefaults(
        themeName: String,
        primitiveType: String?,
        sourceType: String,
    ): JsonObject {
        val theme = registeredTheme(themeName) ?: return EMPTY_OBJECT
        val merged = linkedMapOf<String, JsonElement>()
        for (
            key in listOfNotNull(
                "elements",
                primitiveType,
                sourceType,
            ).distinct()
        ) {
            val values = theme[key] as? JsonObject ?: continue
            mergeInto(merged, lowerKeys(values))
        }
        return JsonObject(merged)
    }

    private fun optionTree(
        vararg entries: Pair<String, Any>,
    ): JsonObject {
        val root = linkedMapOf<String, Any>()
        for ((path, value) in entries) {
            val parts = path.split('.')
            var target: MutableMap<String, Any> = root
            for (part in parts.dropLast(1)) {
                @Suppress("UNCHECKED_CAST")
                target = target.getOrPut(part) {
                    linkedMapOf<String, Any>()
                } as MutableMap<String, Any>
            }
            target[parts.last()] = value
        }
        return toJsonObject(root)
    }

    private fun toJsonObject(
        source: Map<String, Any>,
    ): JsonObject = JsonObject(
        source.mapValues { (_, value) -> toJsonElement(value) },
    )

    private fun toJsonElement(value: Any): JsonElement =
        when (value) {
            is Boolean -> JsonPrimitive(value)
            is Int -> JsonPrimitive(value)
            is Double -> JsonPrimitive(value)
            is String -> JsonPrimitive(value)
            is List<*> -> JsonArray(
                value.map { item ->
                    toJsonElement(requireNotNull(item))
                },
            )
            is Map<*, *> -> {
                @Suppress("UNCHECKED_CAST")
                toJsonObject(value as Map<String, Any>)
            }
            else -> error(
                "Unsupported built-in JSXGraph theme value: " +
                    value::class.simpleName,
            )
        }

    private fun lowerKeys(source: JsonObject): JsonObject =
        JsonObject(
            source.map { (key, value) ->
                key.lowercase() to
                    if (value is JsonObject) {
                        lowerKeys(value)
                    } else {
                        value
                    }
            }.toMap(),
        )

    private fun mergeInto(
        target: MutableMap<String, JsonElement>,
        source: JsonObject,
    ) {
        for ((key, value) in source) {
            val current = target[key]
            target[key] =
                if (current is JsonObject && value is JsonObject) {
                    val nested = current.toMutableMap()
                    mergeInto(nested, value)
                    JsonObject(nested)
                } else {
                    value
                }
        }
    }

    private val EMPTY_OBJECT = JsonObject(emptyMap())
}
